[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
graph = "0.3.1"
graph_builder = "0.4.0"

[profile.profiling]
inherits = "release"
debug = true
